name: Python unit tests

on:
  push:
    branches: [ main,v2 ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflows manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout to given branch
      - uses: actions/checkout@v2

      # Installing python and project dependencies
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          brew install tesseract
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Running project unit tests rom run_tests.py file
      - name: Run unit tests
        run: |
          cd test
          export PYTHONPATH=../
          python -m unittest